# Generated by Django 5.0.1 on 2024-10-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfor',
            old_name='whatsapp_channel_url',
            new_name='whatsapp_url',
        ),
    ]
