# Generated by Django 5.0.1 on 2024-10-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_whatsapp_channel_url_companyinfor_whatsapp_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfor',
            old_name='addres',
            new_name='address',
        ),
    ]
