# Generated by Django 5.0.1 on 2024-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_addres_companyinfor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfor',
            name='call_to_action_message',
            field=models.CharField(default='want a loan', help_text='this is the text that will appear at call to action section', max_length=100),
            preserve_default=False,
        ),
    ]
