# Generated by Django 5.0.1 on 2024-10-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_companyinfor_call_to_action_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='interest_rate_summary',
            new_name='message',
        ),
    ]
